### ISSUE TITLE
Hi, could you please provide brain slice data or open the permissions of the website?

### ISSUE THREAD

**Issue by velonica0** [nitinagarwal/Mouse_Brain_Registration#1]
I want to get some brain slice data , but  can‘t get the zip.
It show:
Forbidden
You don't have permission to access /~agarwal/mouseBrain/mouse_registration.zip on this server.

Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips SVN/1.7.14 Server at www.ics.uci.edu Port 80

**Comment by nitinagarwal** [comment]
You should be able to access the data from the below links:
1. https://drive.google.com/file/d/1kLYE7MO9M5vgsILbkeJk0nwoyJfhDIB3/view?usp=sharing
2. https://drive.google.com/file/d/1rjmFQSXHAhcD-WhYc2SlLJ5VKczs_hCV/view?usp=sharing

**Comment by velonica0** [comment]
> You should be able to access the data from the below links:

Thank you for your provision.
And I have some questions about the paper and would like to communicate with you, the email has been sent to your email 
address found through GitHub. If you don't receive it, could you provide the latest email address?
Thanks a lot.

**Comment by nitinagarwal** [comment]
you can email me at `agarwaln@csm.ai`
